select * FROM actor; 
SELECT first_name FROM actor;
SELECT actor_id,first_name,last_update FROM actor;
SELECT city from city where city_id > 5;
SELECT category_id as category FROM film_category;
SELECT first_name from customer ORDER BY address_id ASC;
select customer_id as paid from payment order by amount;
select actor_id as id, first_name, last_name from actor order by last_update ;
select actor_id ,length(first_name)  from actor;
select first_name from actor order by actor_id desc ;
select country from country  order by country_id ;
select country from country  order by length(country) < 8;
select distinct city from city;
select first_name,last_name from actor where first_name like '%er%' ;
select payment_id, customer_id from payment  where amount between 6 and 9;
select payment_id, customer_id from payment  where amount not  between 6 and 9;
insert into actor  (first_name ,last_name) values('john', 'Dillinger');
select * from rental,payment;
select customer_id from payment  order by rental_id,amount;
select title , description from film order by release_year;