# Generated by Django 4.1.4 on 2022-12-14 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_alter_reminder_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='due_date',
        ),
        migrations.AddField(
            model_name='reminder',
            name='due_date_new',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
