# Generated by Django 4.1.4 on 2022-12-14 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_remove_reminder_due_date_reminder_due_date_new'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='due_date_new',
            new_name='due_date',
        ),
    ]
