# Generated by Django 4.1.4 on 2022-12-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_stuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='stuff',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
