version: '3.9'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:5000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - app-tier

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
