# Generated by Django 4.1.4 on 2022-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_rename_due_date_reminder_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=None),
        ),
    ]
