# Generated by Django 4.1.4 on 2022-12-14 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_alter_reminder_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='due_date',
            field=models.DateField(default=datetime.date(2022, 12, 14)),
        ),
    ]
