# Generated by Django 4.1.6 on 2023-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("win", models.IntegerField()),
                ("mac", models.IntegerField()),
                ("linux", models.IntegerField()),
                ("other", models.IntegerField()),
            ],
        ),
    ]
