version: '3.9'

services:

  api:
    build:
      context: ./services/backend      
      dockerfile: Dockerfile
    ports:
      - 5050:5000
      - 4444:4444
    environment:
      - FLASK_DEBUG=true
      - APP_SETTINGS=config.DevelopmentConfig
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DOCKER_ONLY=true
    volumes:
      - ./services/backend:/code
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis:/data

  postgres:
    build:
      context: ./services/db
      dockerfile: Dockerfile    
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - api

volumes: 
  redis:
    driver: local