# Generated by Django 4.1.5 on 2023-01-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="done",
            field=models.BooleanField(default=False),
        ),
    ]
