# Generated by Django 4.1.5 on 2023-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_num", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=50)),
                ("date", models.DateField(auto_now_add=True)),
                ("price", models.FloatField()),
            ],
        ),
    ]
