# Generated by Django 3.2.16 on 2023-01-04 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230104_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='last_sold_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='rentzestimate_last_updated',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='zestimate_last_updated',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
