# Generated by Django 4.1.6 on 2023-02-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_lineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="uploads/products"
            ),
        ),
    ]
