# Generated by Django 4.1.4 on 2022-12-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payer", models.CharField(max_length=255)),
                ("payee", models.CharField(max_length=255)),
                ("transfer", models.IntegerField()),
            ],
        ),
    ]
