# Generated by Django 4.1.4 on 2022-12-15 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0003_alter_customer_joining_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Transfer",
        ),
    ]
