# Generated by Django 4.1.4 on 2022-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="joining_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
