# Generated by Django 4.1.4 on 2022-12-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_alter_reminder_stuff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='stuff',
        ),
    ]
