# Generated by Django 4.1.6 on 2023-02-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="source_url",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
