# Generated by Django 4.1.6 on 2023-02-03 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0002_alter_url_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="expires",
            field=models.DateField(default=datetime.date(2023, 2, 17)),
        ),
    ]
