# Generated by Django 3.2.16 on 2023-01-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230104_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='area_unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='bathrooms',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='bedrooms',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='home_size',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='home_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='last_sold_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='price',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='property_size',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='rent_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='rentzestimate_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='state',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='tax_value',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='tax_year',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='year_built',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='zestimate_amount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='zillow_id',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='houses',
            name='zipcode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
