# Generated by Django 3.2.16 on 2023-01-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20230105_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='location_id',
            new_name='location',
        ),
    ]
